// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBppwhf7FtkD7R6d61cRYN5s3NOtrPGw1E',
    appId: '1:556031650608:web:739b24ab5c58cf7b6cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-kbm-app',
    authDomain: 'marketing-kbm-app.firebaseapp.com',
    databaseURL: 'https://marketing-kbm-app-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-kbm-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkOyKdd-G6FzagS53WHvbEqnnUI5T3Vk',
    appId: '1:556031650608:android:8080279ae7da0b826cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-kbm-app',
    databaseURL: 'https://marketing-kbm-app-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-kbm-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJD_YwC3DMoB9m9DNWX3zZkJjcz8AlDr8',
    appId: '1:556031650608:ios:1ba632eafdcc58a96cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-kbm-app',
    databaseURL: 'https://marketing-kbm-app-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-kbm-app.firebasestorage.app',
    iosClientId: '556031650608-0m5073mtf14vsdeib04f5sirqootdhbh.apps.googleusercontent.com',
    iosBundleId: 'com.kbmgroup.marketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBppwhf7FtkD7R6d61cRYN5s3NOtrPGw1E',
    appId: '1:556031650608:web:9575c9ac562c5e036cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-kbm-app',
    authDomain: 'marketing-kbm-app.firebaseapp.com',
    databaseURL: 'https://marketing-kbm-app-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-kbm-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJD_YwC3DMoB9m9DNWX3zZkJjcz8AlDr8',
    appId: '1:556031650608:ios:7cc3bdea1103a76f6cb6f5',
    messagingSenderId: '556031650608',
    projectId: 'marketing-kbm-app',
    databaseURL: 'https://marketing-kbm-app-default-rtdb.firebaseio.com',
    storageBucket: 'marketing-kbm-app.firebasestorage.app',
    iosClientId: '556031650608-8ckg1654u797nlrdjm0kfg1kcqkdc3au.apps.googleusercontent.com',
    iosBundleId: 'com.example.markatingKbmApp',
  );

}